CREATE TABLE `CITI_FUND_ASSET` (
  `KEY` int(11) NOT NULL AUTO_INCREMENT,
  `ISIN` varchar(15) CHARACTER SET utf8 DEFAULT NULL,
  `STRATEGY_KEY` varchar(15) COLLATE utf8_bin DEFAULT NULL,
  `CITI_FUND_CODE` varchar(25) COLLATE utf8_bin DEFAULT NULL,
  `CITI_FUND_NAME` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `CITI_TTS` (
  `KEY` int(11) NOT NULL AUTO_INCREMENT,
  `LANGUAGE` varchar(6) CHARACTER SET utf8 DEFAULT NULL,
  `KFS_FILE_URL` varchar(500) CHARACTER SET utf8 DEFAULT NULL,
  `CITI_FUND_ASSET_KEY` int(11) NOT NULL,
  `TTS_TEXT` mediumtext COLLATE utf8_bin,
  PRIMARY KEY (`KEY`),
  KEY `fk_CITI_TTS_1_idx` (`CITI_FUND_ASSET_KEY`),
  CONSTRAINT `fk_CITI_TTS_1` FOREIGN KEY (`CITI_FUND_ASSET_KEY`) REFERENCES `CITI_FUND_ASSET` (`KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=113 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `CITI_TTS_AUDIT_HIST` (
  `ISIN` varchar(15) CHARACTER SET utf8 DEFAULT NULL,
  `STRATEGY_KEY` varchar(15) COLLATE utf8_bin DEFAULT NULL,
  `SESSION_PIN` int(3) DEFAULT NULL,
  `LANGUAGE` varchar(6) COLLATE utf8_bin DEFAULT NULL,
  `CREATED_TIMESTAMP` datetime DEFAULT NULL,
  `LAST_UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `MOBILE_NO` varchar(15) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `CITI_TTS_PIN` (
  `KEY` int(11) NOT NULL AUTO_INCREMENT,
  `SESSION_PIN` int(3) DEFAULT NULL,
  `CREATED_TIMESTAMP` datetime DEFAULT NULL,
  `LAST_UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `CITI_TTS_KEY` int(11) NOT NULL,
  PRIMARY KEY (`KEY`),
  UNIQUE KEY `SESSIPN_PIN_UNIQUE` (`SESSION_PIN`),
  KEY `fk_CITI_TTS_PIN_1_idx` (`CITI_TTS_KEY`),
  CONSTRAINT `fk_CITI_TTS_PIN_1` FOREIGN KEY (`CITI_TTS_KEY`) REFERENCES `CITI_TTS` (`KEY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=564 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `TTS_CONFIG` (
  `CLIENT_CODE` varchar(15) COLLATE utf8_bin NOT NULL,
  `CONFIG_NAME` varchar(100) CHARACTER SET utf8 NOT NULL,
  `CONFIG_VALUE` varchar(255) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `TTS_TEXT_CHANGE_LOG` (
  `ASSET_KEY` VARCHAR(15) NULL,
  `LANGUAGE` VARCHAR(6) NULL,
  `OLD_TTS_TEXT` MEDIUMTEXT NULL,
  `NEW_TTS_TEXT` MEDIUMTEXT NULL,
  `CREATED_TIMESTAMP` DATETIME NULL);
